name: Run tests when test code changes on PR

on:
  pull_request:
    paths:
      - 'demo/src/test/java/**'
      - 'demo/src/main/java/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Javaをセットアップ
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Mavenでテスト実行
        run: mvn -f demo/pom.xml test
